import { launch, BASE, sleep } from './drv.mjs';
import { waitMain } from './walk.mjs';
import fs from 'node:fs';
const id = fs.readFileSync('brioche-id.txt', 'utf8').trim();
const G = fs.readFileSync('group2-id.txt', 'utf8').trim();
const { browser, page, net } = await launch({ storageState: 'state-qa1.json' });
const go = async (u, sel = 'main') => { await page.goto(BASE + u); await waitMain(page, sel); await sleep(1800); };
const controls = async () => JSON.stringify(await page.locator('button, a, summary, input, select, textarea, [role=tab]').evaluateAll((els) => els.map((e) => `${e.tagName.toLowerCase()}${e.type ? ':' + e.type : ''}=${(e.getAttribute('aria-label') || e.textContent || e.placeholder || e.name || '').trim().slice(0, 40)}`).filter(Boolean)));
await go(`/recipe/${id}`);
console.log('IMG', JSON.stringify(await page.locator('img').evaluateAll((els) => els.map((e) => ({ alt: e.alt, ok: e.complete && e.naturalWidth > 0, src: e.src.slice(0, 60) })))));
console.log('RECIPE controls:', await controls());
await page.locator('summary').filter({ hasText: 'פרטים מקצועיים' }).click(); await sleep(600);
console.log('RECIPE details controls:', await controls());
await page.getByRole('button', { name: /קמח לחם/ }).first().click(); await sleep(700);
const cal = page.getByRole('button', { name: /לכייל/ }).first();
console.log('CAL box', JSON.stringify(await cal.boundingBox()), 'visible', await cal.isVisible());
await cal.click({ timeout: 5000 }).catch((e) => console.log('cal click err', String(e).slice(0, 200)));
await sleep(600);
console.log('AFTER CAL:', (await page.locator('body').innerText()).replace(/\s+/g, ' ').slice(0, 700));
await page.screenshot({ path: '/home/user/recipe-notebook/artifact/qa/shots-accept/probe-calibrate.png' });
await go(`/group/${G}`);
console.log('GROUP controls:', await controls());
await go('/settings');
console.log('SETTINGS controls:', await controls());
console.log('NET', JSON.stringify(net.filter((n) => n.s >= 400).map((n) => `${n.m} ${n.u.slice(0, 120)} ${n.s}`)));
await browser.close();
